using System.Collections.Generic;
namespace me.coldandtired.mcg.Models
{
    public class Item_types : List<Data_type>
    {
        public Item_types()
        {
            Add(new Data_type { display_name = "Insert type" });
            Add(new Data_type { display_name = "Air (nothing)", name = "0" });
            Add(new Data_type { display_name = "Apple", name = "260" });
            Add(new Data_type { display_name = "Arrow", name = "262" });
            Add(new Data_type { display_name = "Bed", name = "355" });
            Add(new Data_type { display_name = "Bedrock", name = "7" });
            Add(new Data_type { display_name = "Bed block", name = "26" });
            Add(new Data_type { display_name = "Blaze powder", name = "377" });
            Add(new Data_type { display_name = "Blaze rod", name = "369" });
            Add(new Data_type { display_name = "Boat", name = "333" });
            Add(new Data_type { display_name = "Bone", name = "352" });
            Add(new Data_type { display_name = "Book", name = "340" });
            Add(new Data_type { display_name = "Bookshelf", name = "47" });
            Add(new Data_type { display_name = "Bow", name = "261" });
            Add(new Data_type { display_name = "Bowl", name = "281" });
            Add(new Data_type { display_name = "Bread", name = "297" });
            Add(new Data_type { display_name = "Brewing stand", name = "117" });
            Add(new Data_type { display_name = "Brewing stand item", name = "379" });
            Add(new Data_type { display_name = "Brick", name = "45" });
            Add(new Data_type { display_name = "Brick stairs", name = "108" });
            Add(new Data_type { display_name = "Brown mushroom", name = "39" });
            Add(new Data_type { display_name = "Bucket", name = "325" });
            Add(new Data_type { display_name = "Burning furnace", name = "62" });
            Add(new Data_type { display_name = "Cactus", name = "81" });
            Add(new Data_type { display_name = "Cake", name = "354" });
            Add(new Data_type { display_name = "Cake block", name = "92" });
            Add(new Data_type { display_name = "Cauldron", name = "118" });
            Add(new Data_type { display_name = "Cauldron item", name = "380" });
            Add(new Data_type { display_name = "Chainmail boots", name = "305" });
            Add(new Data_type { display_name = "Chainmail chestplate", name = "303" });
            Add(new Data_type { display_name = "Chainmail helmet", name = "302" });
            Add(new Data_type { display_name = "Chainmail leggings", name = "304" });
            Add(new Data_type { display_name = "Chest", name = "54" });
            Add(new Data_type { display_name = "Clay", name = "82" });
            Add(new Data_type { display_name = "Clay ball", name = "337" });
            Add(new Data_type { display_name = "Clay brick", name = "336" });
            Add(new Data_type { display_name = "Coal", name = "263" });
            Add(new Data_type { display_name = "Coal ore", name = "16" });
            Add(new Data_type { display_name = "Cobblestone", name = "4" });
            Add(new Data_type { display_name = "Cobblestone stairs", name = "67" });
            Add(new Data_type { display_name = "Compass", name = "345" });
            Add(new Data_type { display_name = "Cooked beef", name = "364" });
            Add(new Data_type { display_name = "Cooked chicken", name = "366" });
            Add(new Data_type { display_name = "Cooked fish", name = "350" });
            Add(new Data_type { display_name = "Cookie", name = "357" });
            Add(new Data_type { display_name = "Crops", name = "59" });
            Add(new Data_type { display_name = "Dead bush", name = "32" });
            Add(new Data_type { display_name = "Detector rail", name = "28" });
            Add(new Data_type { display_name = "Diamond", name = "264" });
            Add(new Data_type { display_name = "Diamond axe", name = "279" });
            Add(new Data_type { display_name = "Diamond block", name = "57" });
            Add(new Data_type { display_name = "Diamond boots", name = "313" });
            Add(new Data_type { display_name = "Diamond chestplate", name = "311" });
            Add(new Data_type { display_name = "Diamond helmet", name = "310" });
            Add(new Data_type { display_name = "Diamond hoe", name = "293" });
            Add(new Data_type { display_name = "Diamond leggings", name = "312" });
            Add(new Data_type { display_name = "Diamond ore", name = "56" });
            Add(new Data_type { display_name = "Diamond pickaxe", name = "278" });
            Add(new Data_type { display_name = "Diamond spade", name = "277" });
            Add(new Data_type { display_name = "Diamond sword", name = "276" });
            Add(new Data_type { display_name = "Diode", name = "356" });
            Add(new Data_type { display_name = "Diode block off", name = "93" });
            Add(new Data_type { display_name = "Diode block on", name = "94" });
            Add(new Data_type { display_name = "Dirt", name = "3" });
            Add(new Data_type { display_name = "Dispenser", name = "23" });
            Add(new Data_type { display_name = "Double step", name = "43" });
            Add(new Data_type { display_name = "Dragon egg", name = "122" });
            Add(new Data_type { display_name = "Egg", name = "344" });
            Add(new Data_type { display_name = "Enchantment table", name = "116" });
            Add(new Data_type { display_name = "Ender pearl", name = "368" });
            Add(new Data_type { display_name = "Ender portal", name = "119" });
            Add(new Data_type { display_name = "Ender portal frame", name = "120" });
            Add(new Data_type { display_name = "Ender stone", name = "121" });
            Add(new Data_type { display_name = "Exp bottle", name = "384" });
            Add(new Data_type { display_name = "Eye of ender", name = "381" });
            Add(new Data_type { display_name = "Feather", name = "288" });
            Add(new Data_type { display_name = "Fence", name = "85" });
            Add(new Data_type { display_name = "Fence gate", name = "107" });
            Add(new Data_type { display_name = "Fermented spider eye", name = "376" });
            Add(new Data_type { display_name = "Fire", name = "51" });
            Add(new Data_type { display_name = "Fireball", name = "385" });
            Add(new Data_type { display_name = "Fishing rod", name = "346" });
            Add(new Data_type { display_name = "Flint", name = "318" });
            Add(new Data_type { display_name = "Flint and steel", name = "259" });
            Add(new Data_type { display_name = "Furnace", name = "61" });
            Add(new Data_type { display_name = "Ghast tear", name = "370" });
            Add(new Data_type { display_name = "Glass", name = "20" });
            Add(new Data_type { display_name = "Glass bottle", name = "374" });
            Add(new Data_type { display_name = "Glowing redstone ore", name = "74" });
            Add(new Data_type { display_name = "Glowstone", name = "89" });
            Add(new Data_type { display_name = "Glowstone dust", name = "348" });
            Add(new Data_type { display_name = "Golden apple", name = "322" });
            Add(new Data_type { display_name = "Gold axe", name = "286" });
            Add(new Data_type { display_name = "Gold block", name = "41" });
            Add(new Data_type { display_name = "Gold boots", name = "317" });
            Add(new Data_type { display_name = "Gold chestplate", name = "315" });
            Add(new Data_type { display_name = "Gold helmet", name = "314" });
            Add(new Data_type { display_name = "Gold hoe", name = "294" });
            Add(new Data_type { display_name = "Gold ingot", name = "266" });
            Add(new Data_type { display_name = "Gold leggings", name = "316" });
            Add(new Data_type { display_name = "Gold nugget", name = "371" });
            Add(new Data_type { display_name = "Gold ore", name = "14" });
            Add(new Data_type { display_name = "Gold pickaxe", name = "285" });
            Add(new Data_type { display_name = "Gold record", name = "2256" });
            Add(new Data_type { display_name = "Gold spade", name = "284" });
            Add(new Data_type { display_name = "Gold sword", name = "283" });
            Add(new Data_type { display_name = "Grass", name = "2" });
            Add(new Data_type { display_name = "Gravel", name = "13" });
            Add(new Data_type { display_name = "Green record", name = "2257" });
            Add(new Data_type { display_name = "Grilled pork", name = "320" });
            Add(new Data_type { display_name = "Huge mushroom 1", name = "99" });
            Add(new Data_type { display_name = "Huge mushroom 2", name = "100" });
            Add(new Data_type { display_name = "Ice", name = "79" });
            Add(new Data_type { display_name = "Ink sack", name = "351" });
            Add(new Data_type { display_name = "Iron axe", name = "258" });
            Add(new Data_type { display_name = "Iron block", name = "42" });
            Add(new Data_type { display_name = "Iron boots", name = "309" });
            Add(new Data_type { display_name = "Iron chestplate", name = "307" });
            Add(new Data_type { display_name = "Iron door", name = "330" });
            Add(new Data_type { display_name = "Iron door block", name = "71" });
            Add(new Data_type { display_name = "Iron fence", name = "101" });
            Add(new Data_type { display_name = "Iron helmet", name = "306" });
            Add(new Data_type { display_name = "Iron hoe", name = "292" });
            Add(new Data_type { display_name = "Iron ingot", name = "265" });
            Add(new Data_type { display_name = "Iron leggings", name = "308" });
            Add(new Data_type { display_name = "Iron ore", name = "15" });
            Add(new Data_type { display_name = "Iron pickaxe", name = "257" });
            Add(new Data_type { display_name = "Iron spade", name = "256" });
            Add(new Data_type { display_name = "Iron sword", name = "267" });
            Add(new Data_type { display_name = "Jack o lantern", name = "91" });
            Add(new Data_type { display_name = "Jukebox", name = "84" });
            Add(new Data_type { display_name = "Ladder", name = "65" });
            Add(new Data_type { display_name = "Lapis block", name = "22" });
            Add(new Data_type { display_name = "Lapis ore", name = "21" });
            Add(new Data_type { display_name = "Lava", name = "10" });
            Add(new Data_type { display_name = "Lava bucket", name = "327" });
            Add(new Data_type { display_name = "Leather", name = "334" });
            Add(new Data_type { display_name = "Leather boots", name = "301" });
            Add(new Data_type { display_name = "Leather chestplate", name = "299" });
            Add(new Data_type { display_name = "Leather helmet", name = "298" });
            Add(new Data_type { display_name = "Leather leggings", name = "300" });
            Add(new Data_type { display_name = "Leaves", name = "18" });
            Add(new Data_type { display_name = "Lever", name = "69" });
            Add(new Data_type { display_name = "Locked chest", name = "95" });
            Add(new Data_type { display_name = "Log", name = "17" });
            Add(new Data_type { display_name = "Long grass", name = "31" });
            Add(new Data_type { display_name = "Magma cream", name = "378" });
            Add(new Data_type { display_name = "Map", name = "358" });
            Add(new Data_type { display_name = "Melon", name = "360" });
            Add(new Data_type { display_name = "Melon block", name = "103" });
            Add(new Data_type { display_name = "Melon seeds", name = "362" });
            Add(new Data_type { display_name = "Melon stem", name = "105" });
            Add(new Data_type { display_name = "Milk bucket", name = "335" });
            Add(new Data_type { display_name = "Minecart", name = "328" });
            Add(new Data_type { display_name = "Mob spawner", name = "52" });
            Add(new Data_type { display_name = "Monster egg", name = "383" });
            Add(new Data_type { display_name = "Monster eggs", name = "97" });
            Add(new Data_type { display_name = "Mossy cobblestone", name = "48" });
            Add(new Data_type { display_name = "Mushroom soup", name = "282" });
            Add(new Data_type { display_name = "Mycel", name = "110" });
            Add(new Data_type { display_name = "Netherrack", name = "87" });
            Add(new Data_type { display_name = "Nether brick", name = "112" });
            Add(new Data_type { display_name = "Nether brick stairs", name = "114" });
            Add(new Data_type { display_name = "Nether fence", name = "113" });
            Add(new Data_type { display_name = "Nether stalk", name = "372" });
            Add(new Data_type { display_name = "Nether warts", name = "115" });
            Add(new Data_type { display_name = "Note block", name = "25" });
            Add(new Data_type { display_name = "Obsidian", name = "49" });
            Add(new Data_type { display_name = "Painting", name = "321" });
            Add(new Data_type { display_name = "Paper", name = "339" });
            Add(new Data_type { display_name = "Piston base", name = "33" });
            Add(new Data_type { display_name = "Piston extension", name = "34" });
            Add(new Data_type { display_name = "Piston moving piece", name = "36" });
            Add(new Data_type { display_name = "Piston sticky base", name = "29" });
            Add(new Data_type { display_name = "Pork", name = "319" });
            Add(new Data_type { display_name = "Portal", name = "90" });
            Add(new Data_type { display_name = "Potion", name = "373" });
            Add(new Data_type { display_name = "Powered minecart", name = "343" });
            Add(new Data_type { display_name = "Powered rail", name = "27" });
            Add(new Data_type { display_name = "Pumpkin", name = "86" });
            Add(new Data_type { display_name = "Pumpkin seeds", name = "361" });
            Add(new Data_type { display_name = "Pumpkin stem", name = "104" });
            Add(new Data_type { display_name = "Rails", name = "66" });
            Add(new Data_type { display_name = "Raw beef", name = "363" });
            Add(new Data_type { display_name = "Raw chicken", name = "365" });
            Add(new Data_type { display_name = "Raw fish", name = "349" });
            Add(new Data_type { display_name = "Record 10", name = "2265" });
            Add(new Data_type { display_name = "Record 11", name = "2266" });
            Add(new Data_type { display_name = "Record 3", name = "2258" });
            Add(new Data_type { display_name = "Record 4", name = "2259" });
            Add(new Data_type { display_name = "Record 5", name = "2260" });
            Add(new Data_type { display_name = "Record 6", name = "2261" });
            Add(new Data_type { display_name = "Record 7", name = "2262" });
            Add(new Data_type { display_name = "Record 8", name = "2263" });
            Add(new Data_type { display_name = "Record 9", name = "2264" });
            Add(new Data_type { display_name = "Redstone", name = "331" });
            Add(new Data_type { display_name = "Redstone lamp off", name = "123" });
            Add(new Data_type { display_name = "Redstone lamp on", name = "124" });
            Add(new Data_type { display_name = "Redstone ore", name = "73" });
            Add(new Data_type { display_name = "Redstone torch off", name = "75" });
            Add(new Data_type { display_name = "Redstone torch on", name = "76" });
            Add(new Data_type { display_name = "Redstone wire", name = "55" });
            Add(new Data_type { display_name = "Red mushroom", name = "40" });
            Add(new Data_type { display_name = "Red rose", name = "38" });
            Add(new Data_type { display_name = "Rotten flesh", name = "367" });
            Add(new Data_type { display_name = "Saddle", name = "329" });
            Add(new Data_type { display_name = "Sand", name = "12" });
            Add(new Data_type { display_name = "Sandstone", name = "24" });
            Add(new Data_type { display_name = "Sapling", name = "6" });
            Add(new Data_type { display_name = "Seeds", name = "295" });
            Add(new Data_type { display_name = "Shears", name = "359" });
            Add(new Data_type { display_name = "Sign", name = "323" });
            Add(new Data_type { display_name = "Sign post", name = "63" });
            Add(new Data_type { display_name = "Slime ball", name = "341" });
            Add(new Data_type { display_name = "Smooth brick", name = "98" });
            Add(new Data_type { display_name = "Smooth stairs", name = "109" });
            Add(new Data_type { display_name = "Snow", name = "78" });
            Add(new Data_type { display_name = "Snow ball", name = "332" });
            Add(new Data_type { display_name = "Snow block", name = "80" });
            Add(new Data_type { display_name = "Soil", name = "60" });
            Add(new Data_type { display_name = "Soul sand", name = "88" });
            Add(new Data_type { display_name = "Speckled melon", name = "382" });
            Add(new Data_type { display_name = "Spider eye", name = "375" });
            Add(new Data_type { display_name = "Sponge", name = "19" });
            Add(new Data_type { display_name = "Stationary lava", name = "11" });
            Add(new Data_type { display_name = "Stationary water", name = "9" });
            Add(new Data_type { display_name = "Step", name = "44" });
            Add(new Data_type { display_name = "Stick", name = "280" });
            Add(new Data_type { display_name = "Stone", name = "1" });
            Add(new Data_type { display_name = "Stone axe", name = "275" });
            Add(new Data_type { display_name = "Stone button", name = "77" });
            Add(new Data_type { display_name = "Stone hoe", name = "291" });
            Add(new Data_type { display_name = "Stone pickaxe", name = "274" });
            Add(new Data_type { display_name = "Stone plate", name = "70" });
            Add(new Data_type { display_name = "Stone spade", name = "273" });
            Add(new Data_type { display_name = "Stone sword", name = "272" });
            Add(new Data_type { display_name = "Storage minecart", name = "342" });
            Add(new Data_type { display_name = "String", name = "287" });
            Add(new Data_type { display_name = "Sugar", name = "353" });
            Add(new Data_type { display_name = "Sugar cane", name = "338" });
            Add(new Data_type { display_name = "Sugar cane block", name = "83" });
            Add(new Data_type { display_name = "Sulphur", name = "289" });
            Add(new Data_type { display_name = "Thin glass", name = "102" });
            Add(new Data_type { display_name = "Tnt", name = "46" });
            Add(new Data_type { display_name = "Torch", name = "50" });
            Add(new Data_type { display_name = "Trap door", name = "96" });
            Add(new Data_type { display_name = "Vine", name = "106" });
            Add(new Data_type { display_name = "Wall sign", name = "68" });
            Add(new Data_type { display_name = "Watch", name = "347" });
            Add(new Data_type { display_name = "Water", name = "8" });
            Add(new Data_type { display_name = "Water bucket", name = "326" });
            Add(new Data_type { display_name = "Water lily", name = "111" });
            Add(new Data_type { display_name = "Web", name = "30" });
            Add(new Data_type { display_name = "Wheat", name = "296" });
            Add(new Data_type { display_name = "Wood", name = "5" });
            Add(new Data_type { display_name = "Wooden door", name = "64" });
            Add(new Data_type { display_name = "Wood axe", name = "271" });
            Add(new Data_type { display_name = "Wood door", name = "324" });
            Add(new Data_type { display_name = "Wood hoe", name = "290" });
            Add(new Data_type { display_name = "Wood pickaxe", name = "270" });
            Add(new Data_type { display_name = "Wood plate", name = "72" });
            Add(new Data_type { display_name = "Wood spade", name = "269" });
            Add(new Data_type { display_name = "Wood stairs", name = "53" });
            Add(new Data_type { display_name = "Wood sword", name = "268" });
            Add(new Data_type { display_name = "Wool", name = "35", data_type = "wool" });
            Add(new Data_type { display_name = "Workbench", name = "58" });
            Add(new Data_type { display_name = "Yellow flower", name = "37" });
        }

        public void insert_extra_values()
        {
            Insert(1, new Data_type { display_name = "Default", name = "default" });
            Insert(2, new Data_type { display_name = "Random", name = "random" });
        }
    }
}
